image: cypress/base:14.16.0

before_script:
    - npm install

pages:
    stage: deploy
    script:
        - npm test || true
        - mv mochawesome-report public
    artifacts:
        paths:
            - public
